### ISSUE TITLE
indicator disappears when you click outstide

### ISSUE THREAD

**Issue by gilbertngandu** [Initsogar/cordova-activityindicator#13]
Hi I want to be able to prevent the dialog from disappearing when you click outside the dialog.

**Comment by ginamdar** [comment]
I think this is an android issue and you can pass parameter as cancelable as false in AndroidProgressHUD.java#show but I dont think there the api from script side has any parameter to support it

**Comment by dannywillems** [comment]
This pull request is functional: https://github.com/Initsogar/cordova-activityindicator/pull/14.

**Comment by rvdfox** [comment]
is there any callback function to ActivityIndicator?

**Comment by victorsosa** [comment]
@Initsogar why this is not had been merge?

**Comment by victorsosa** [comment]
@Initsogar can you add me as Collaborator to this project, I want to keep this project alive.

**Comment by shivam5x** [comment]
Hi,
Is this resolved above issue? I am getting this issue in case of android vary badly ,please let us know if any update.

Thanks

**Comment by dannywillems** [comment]
My PR has been accepted --> #14.

**Comment by Initsogar** [comment]
Sorry guys, I've been literally disconnected from this project. Now #14 has been merged.

**Comment by victorsosa** [comment]
@Initsogar you can add me as Collaborator to this project, so in case you are busy, someone else can response to the PR and issues.

**Comment by Initsogar** [comment]
@victorsosa I just sent you an invite!

**Comment by victorsosa** [comment]
@Initsogar thanks
